### ISSUE TITLE
looking for a maintainer?

### ISSUE THREAD

**Issue by shackbarth** [segmentio/pg-escape#13]
I think this is a great little library but it does need a bit of love. I asked @tj if he'd like me to help maintain it and he said that sounded good. But it might take someone at segmentio to add me to the team maybe?

https://www.npmjs.com/~shackbarth
https://github.com/shackbarth

**Comment by vitaly-t** [comment]
@shackbarth have you seen [pg-promise](https://github.com/vitaly-t/pg-promise)? It rather gives love than waits for it :) :) :)

**Comment by shackbarth** [comment]
That's an impressive project, but really all I need is a quick synchronous utility that escapes my identifiers the way that https://github.com/brianc/node-postgres natively can parameterize my literals. This project (especially if certain extant PRs were merged) would fit that bill perfectly.

**Comment by vitaly-t** [comment]
@shackbarth pg-promise can do that, and much more.

Example of using the formatting routine outside of the queries:
```js
var format = require('pg-promise').as.format;
var s = format("$1 $2", ['Hello', 'World!']);
console.log(s);
```
outputs:
```
'Hello' 'World!'
```

**Comment by joshgillies** [comment]
Yeah landing this would be excellent: #5

**Comment by rpedela** [comment]
You are welcome to use: https://github.com/datalanche/node-pg-format

It is a Javascript implementation of PG's format(), a superset of pg-escape. I am happy to resolve issues or take PRs.

**Comment by vitaly-t** [comment]
[pg-promise](https://github.com/vitaly-t/pg-promise) supports the following formatting:

* Using standard syntax `$1, $2, ...`
* Using flexible [Named Parameters](https://github.com/vitaly-t/pg-promise#named-parameters) formatting
* [Raw-Text](https://github.com/vitaly-t/pg-promise#raw-text) variable formatting
* [Custom Type Formatting](https://github.com/vitaly-t/pg-promise#custom-type-formatting)
* etc...

And the best part, if you do not want to use the database layer, only the query formatting - you don't have to, the library exposes the formatting methods independently, as shown below:

```js
var format = require('pg-promise').as.format;
var s = format("SELECT * FROM table WHERE field1 = $1 AND field2 = $2", ['one', 123]);
console.log(s);
```
**Output:**
```
SELECT * FROM table WHERE field1 = 'one' AND field2 = 123
```

**Comment by shackbarth** [comment]
@rpedela Thanks, https://github.com/datalanche/node-pg-format is just what I need. It's a drop-in replacement for this project, and https://github.com/datalanche/node-pg-format#formatwitharrayfmt-array is another feature I've been looking for.

@vitaly-t No offense! I just prefer the narrower solution to the problem at hand.

**Comment by vitaly-t** [comment]
@shackbarth That's ok. But I fail to see how is simpler and more limited formatter any better.

**Comment by tj** [comment]
It's fine to suggest something once but marketing on other people's projects is typically not a very respectful thing to do, just mention the alternative and move on :p. I don't have access to the repo anymore but there's no harm in forking

**Comment by vitaly-t** [comment]
@tj Marketing refers to commercial products only. There is nothing commercial here.

But sure, keep it, I was stupid to suggest something better, as they say - ignorance is bliss.

**Comment by mickhansen** [comment]
@vitaly-t How does marketing only apply to commercial products? Non profit organizations use marketing too, marketing is also a valuable tool for open source projects looking to gain traction.

**Comment by kessler** [comment]
@vitaly-t I have to agree with the guys here, you took your "promotions" one step too far. You can be more subtle when offering an alternative, instead of trying to push it. If it is as good as you say, I'm sure it will sell itself.
